const TIPO_VALOR = {
    NUMERO: 'VAL_NUMERO',
    DECIMAL: 'VAL_DECIMAL',
    ID: 'VA_ID',
    STRING: 'VAL_STRING',
}

const TIPO_OPERACION = {
    SUMA: 'OP_SUMA',
    RESTA: 'OP_RESTA',
    MULTIPLICACION: 'OP_MULTIPLICACION',
    DIVISION: 'OP_DIVISION',
    NEGATIVO: 'OP_NEGATIVO',
    MAYOR: 'OP_MAYOR',
    MENOR: 'OP_MENOR',
    MAYOR_IGUAL: 'OP_MAYOR_IGUAL',
    MENOR_IGUAL: 'OP_MENOR_IGUAL',
    IGUALDAD: 'OP_IGUALDAD',
    NO_IGUAL: 'OP_NO_IGUAL',
    AND: 'OP_AND',
    OR: 'OP_OR',
    XOR: 'OP_XOR',XW
}

const TIPO_INSTRUCCION = {
    PRINT: 'INSTR_PRINT',
    IF: 'INSTR_IF',
    WHILE: 'INSTR_WHILE',
    FOR: 'INSTR_FOR',
    ASIGNACION_SIMPLE: 'INSTR_ASIGNACION_SIMPLE',
    DECLARACION_VARIABLE: 'INSTR_DECLARACION_VARIABLE',
    BREAK: 'INSTR_BREAK',
    RETURN_FUNCIONES: 'INSTR_RETURN_FUNCIONES',
    RETURN_METODOS: 'INSTR_RETURN_METODOS',
    CONTINUE: 'INSTR_CONTINUE'
}

module.exports.TIPO_VALOR = TIPO_VALOR;
module.exports.TIPO_OPERACION = TIPO_OPERACION;